### ISSUE TITLE
Increase the contrast on the progress bars

### ISSUE THREAD

**Issue by djcunniffe** [amaximus/transmission-card#10]
In some themes it is hard to tell the progress of the download at a glance. Upping the contrast might help.

![image](https://user-images.githubusercontent.com/32771602/100519414-68571d00-31a0-11eb-8bd2-c370a47829c9.png)

**Comment by amaximus** [comment]
Tried to improve the contrast in the latest release also fixing the color for "Up/Down" status.
Please also note that I tied the colors to theme colors.

Please check on your side too and get back to me with results.

**Comment by djcunniffe** [comment]
Looking better, but will keep testing different scenarios and get back to you

**Comment by amaximus** [comment]
Since the card uses theme colors (instead of the original hardcoded colors), it's up to the theme definition to display a good contrast.
