### ISSUE TITLE
Not Transmission, But how possible will it be to create this for SABNZB?

### ISSUE THREAD

**Issue by Vandiliz3r** [amaximus/transmission-card#11]
I love the Transmission Card, You would be a hero if you can do the same for SABNZB?
Or allow the cards to be modified with different entities.

Regards

**Comment by amaximus** [comment]
I'm not familiar with the SABNZB or NZBGet integrations, so I do not know how the NZB sensors' data and attributes are provided.
You may however clone the Transmission card repo and take it as a base modifying whatever is needed to work with NZB sensors.

**Comment by Vandiliz3r** [comment]
Amaximus, I will have to have a look to see if i understand whats going on. :) But the items are very similar.

**Comment by amaximus** [comment]
You may post here a snapshot about the related sensors and their attributes (what can be seen under Development Tools->States).

**Comment by Vandiliz3r** [comment]
Hey Bud, 
Thanks for the help. 
This is the SABZNB Sensors.
`sensor.sab_daily_total 	
unit_of_measurement: GB
friendly_name: Daily Total

sensor.sab_disk 
unit_of_measurement: GB
friendly_name: Disk Space

sensor.sab_disk_free 	
unit_of_measurement: GB
friendly_name: sab Disk Free

sensor.sab_left 		
unit_of_measurement: MB
friendly_name: Left to download

sensor.sab_monthly_total 	
unit_of_measurement: GB
friendly_name: Monthly Total Downloaded

sensor.sab_queue 	
unit_of_measurement: MB
friendly_name: Queue

sensor.sab_queue_count 	
friendly_name: sab Queue Count

sensor.sab_speed 	
unit_of_measurement: MB/s
friendly_name: Download Speed

sensor.sab_status 	
friendly_name: Status

sensor.sab_total 	
unit_of_measurement: GB
friendly_name: Total Downloaded

sensor.sab_weekly_total 
unit_of_measurement: GB
friendly_name: Weekly Total Downloaded`

Services available:

sabnzbd.set_speed
sabnzbd.pause
sabnzbd.resume

**Comment by amaximus** [comment]
I also meant the states and attributes values from Developer Tools->States (something like to one below for the Transmission sensors).
![screenshot-atticusnas no-ip org_8123-2020 11 30-09_20_11](https://user-images.githubusercontent.com/2511168/100585143-6189f080-32ed-11eb-8250-24ff504bc836.png)

**Comment by Vandiliz3r** [comment]
There seems to be no attributes, just more sensors.
![image](https://user-images.githubusercontent.com/48084630/100585293-027ca980-32f6-11eb-9611-1b6bba6db7d7.png)

**Comment by Vandiliz3r** [comment]
> There seems to be no attributes, just more sensors.
> ![image](https://user-images.githubusercontent.com/48084630/100585293-027ca980-32f6-11eb-9611-1b6bba6db7d7.png)

**Comment by amaximus** [comment]
Is there a sensor with tasks detail from the queue (what is being downloaded, what downloads completed)? Or only these statistics related sensors are available?

**Comment by Vandiliz3r** [comment]
Unfortunately there is not. 
They only have these sensors, But I guess you can calculate the progress on the sensor.sab_left "queue_remaining" sensor?

**Comment by Vandiliz3r** [comment]
Hey Bud, Have you had a chance to look at this again?

**Comment by amaximus** [comment]
Hey, I haven't had time to look into it.

**Comment by amaximus** [comment]
Unfortunately I won't have time for development in the near future, so I'm closing this.
I might come back to this topic later.
