### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by darkleliel** [amaximus/transmission-card#12]
Hi,
Thanks for the great work!
Could you add some functions like:
show/hide turtle mode button
show/hide start/stop button
torrents list options (seems sensor.transmission_total_torrents is default) like sensor.transmission_active_torrents

**Comment by amaximus** [comment]
The requested features have been added in the 0.3.0 version.

Please update the card, check on your side too and get back to me with results.

**Comment by royto** [comment]
Great work.

If I can add something, IMHO i found disturbing to have some parameters with hide (turtle and startstop) and 1 show (type)

I think it will be easier if all were in hide or show ...

**Comment by amaximus** [comment]
You're right. Will push a new release soon.
