### ISSUE TITLE
Overcomplicated

### ISSUE THREAD

**Issue by hellcry37** [amaximus/transmission-card#14]
Hello,

I am using your card and works and looks well. Thank you for your great job.

However, where are you going with it? From a simple useful card to command center for torrents?

The problem that I have with this, is on android home assistant app, card is larger then the screen. Now I can sift all my cards left and right because of this last field that you added (total / active / completed / started). This happens when you switch through them.

I used the options to hide stuff for now it's fine, just consider it please.

Another thing with this toggle is when you press to switch to a new view for example from total to active there is a considerable delay.

**Comment by amaximus** [comment]
Hello,

several new requests came in from community users to add more functionality as the Transmission Integration has a few services available (turtle mode, start/stop of the torrents). It was also requested to show not only the data from the transmission_total_torrents sensor but from the others too (active, completed, paused, etc).

With the new type selector, configuration parameters for hiding these extra elements have also been introduced so users of the card have more control of what they want to display.

To have the initial look of the card, you should set up the card as follows:

```
cards:
    - type: custom:transmission-card
      hide_startstop: true
      hide_turtle: true
```
hide_type defaults to `true`, display_mode to `compact` and default_type to `total` (meaning data from sensor.transmission_total_torrents will be displayed).

I'm also focusing on having backward compatibility when new features are added.
I might have to look into why the type selector overflows. Could you please let me know the resolution of your mobile device?

As for your second topic, the delay: when clicking the type selector that sets the value of a variable that will be taken into consideration at the next invocation of the hass by Home Assistant ([1]).

[1] https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card/

**Comment by hellcry37** [comment]
Hello,

Yes already fixed I noticed new changes and options added and is perfect. I have a OnePlus 8 Pro on FHD+ resolution (2376x1080).

However the new options that you add fixes the thing. Thanks
