### ISSUE TITLE
Error handling for Transmission sensors that do not use default naming convention

### ISSUE THREAD

**Issue by dnguyen800** [amaximus/transmission-card#16]
Thanks for this card, this is much better than the makeshift card I created using Markdown and templates. I had issues setting up the Transmission card initially and noticed my Lovelace dashboard would fail to load. I guessed that the issue had something to do with my messed up Transmission sensor names (I had to re-add the integration, and it created duplicate sensors called 'switch.transmission_turtle_mode_2', etc. I renamed the sensors back to their default naming and the Transmission card works now!

Would it be possible to add in some error handling to check the sensor names, so that it doesn't crash the entire Lovelace dashboard?

**Comment by amaximus** [comment]
The card checks against the default sensor names at [1] and will return and empty array of torrents if the sensor with default transmission name is not found.
What do you mean by 'that it doesn't crash the entire Lovelace dashboard'? How did the dashboard looked like in the case with non-default sensor names? It should have displayed only the title.

[1] https://github.com/amaximus/transmission-card/blob/fe3805db95db62915787d8d46858147aa604245b/transmission-card.js#L10

**Comment by dnguyen800** [comment]
the issue happens with 'switch.transmission_turtle_mode'. If it is renamed to something else, like 'switch.transmission_turtle_mode_2', the Lovelace UI dashboard fails to render like this: 

![image](https://user-images.githubusercontent.com/25126347/103594192-ce744580-4eac-11eb-9462-8cf8a3362c8b.png)

Oddly enough, I don't see any error messages related to this card when using web browser Inspect tool. Once I fix the name of the HA entity back, the HA dashboard renders like this: 

![image](https://user-images.githubusercontent.com/25126347/103594271-07141f00-4ead-11eb-9d3d-f064eb2c67e0.png)

Maybe the issues is with the HA entities that are not sensors?

**Comment by amaximus** [comment]
Support for non-default sensor name has been added recently.

Please update the card and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by dnguyen800** [comment]
The fix works for my needs. If I rename one of the Transmission entities to 'switch.transmission_turtle_mode_2', the rest of the Lovelace dashboard continues to render and only the Transmission card fails to render. It would be helpful if an error message appears, like how errors appear in a red card (see image).
![image](https://user-images.githubusercontent.com/25126347/104529974-d2e0e280-55bf-11eb-98d6-94ca7cf3ada7.png)

**Comment by amaximus** [comment]
I added a fix in the latest 0.6.1 version.

Please update the card and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by dnguyen800** [comment]
I renamed a few Transmission entities and the card continues to work (except for the incorrectly named entities), so this issue can be closed. Thanks!
