### ISSUE TITLE
Сard goes out of bounds

### ISSUE THREAD

**Issue by emela777** [amaximus/transmission-card#17]
Hello.
When zooming, the card goes out of bounds.

![image](https://user-images.githubusercontent.com/22449427/103546340-e1d6df00-4eb3-11eb-91ff-21c3e913e418.png)

**Comment by amaximus** [comment]
Newest release (0.4.2) published couple of secs ago fixes the overflow issue.

Please update the card and get back to me results.

**Comment by amaximus** [comment]
Any update on tetsing the solution?

**Comment by emela777** [comment]
works great, thanks
