### ISSUE TITLE
Transmission entity default name issue

### ISSUE THREAD

**Issue by LorenzoVasi** [amaximus/transmission-card#19]
Hi
I want to report a little issue on code :(

This card works with an predefined entity, called `sensor.transmission_ectect`
If I want change the name of transmission entity, or I want to add another transmission device with another name, this card does't work :(

`Line 10: if (typeof hass.states[**'sensor.transmission_'** + ttype + '_torrents'] != "undefined") {`

I want help you but I don't know so good JS, but i think that u can take the name of entity from an option called `entity` (for example `sensor.transmission_active_torrents`) or other **`sensor.transmissionname`** and report into if with a simple variable :)

Thank u so much for your work 👍

**Comment by amaximus** [comment]
Support for non-default sensor name has been added recently.

Please update the card and get back to me with results.

**Comment by LorenzoVasi** [comment]
It works!!! Thank u so much <3
