### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by hellcry37** [amaximus/transmission-card#2]
Card appears as "undefined" if there are no torrents downloaded in the client.

**Comment by amaximus** [comment]
Fixed in 0.0.4,

Please check and get back to me with results.

**Comment by hellcry37** [comment]
All seem to be ok. Great job, Thank you.

**Comment by mikesrus** [comment]
still affected in 0.1.0

**Comment by amaximus** [comment]
Could you please check the sensor.transmission_total_torrents attributes. You could maybe add a screenshot from the Developer Tools->States.

**Comment by mikesrus** [comment]
there is
`torrent_info:
  Harry.Potter.And.The.Goblet.Of.Fire.2005.2160p.BluRay.REMUX.HEVC.DTS-X.7.1.IVA(6xRUS.2xUKR.ENG.GER).mkv:
    added_date: 1600283443
    percent_done: '100.00'
    status: stopped
    id: 1
unit_of_measurement: Torrents
friendly_name: Transmission Total Torrents
`

![image](https://user-images.githubusercontent.com/15717372/100269199-3313ba80-2f67-11eb-9e57-9cbb13ddd54a.png)

**Comment by amaximus** [comment]
Some error/warning messages from the browser's console would help a lot.

**Comment by mikesrus** [comment]
i have no errors
![Снимок экрана от 2020-11-25 22-32-45](https://user-images.githubusercontent.com/15717372/100273679-352d4780-2f6e-11eb-9489-e7d54f333cb7.png)

**Comment by amaximus** [comment]
Seems like your sensor.transmission_total_torrents state is set to a different number than the number of torrents you have (1). Could you please check the state value of the sensor.transmission_total_torrents? Does it have the same value as the real number of torrents?

**Comment by mikesrus** [comment]
sensor.transmission_total_torrents state equal to real number of torrents (running paused and seed etc..) and torrent with displayed in card have ID 1 in transmisson

in other card i see correct number of torrents
![image](https://user-images.githubusercontent.com/15717372/100277133-b2a78680-2f73-11eb-99d6-734497754189.png)
