### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by vsimanin** [amaximus/transmission-card#25]
On version HA 2021.11. *, the icon pack has been updated. 
Now they are not displayed on your card.
![55](https://user-images.githubusercontent.com/9263449/142677372-a223a45c-c17f-4721-815d-67c8349e6cf2.PNG)
The buttons work, but the icon is not displayed!

**Comment by amaximus** [comment]
Newest release (0.8.2) fixes the icons issue.

Please update the card and get back to me with results.

**Comment by vsimanin** [comment]
> Newest release (0.8.2) fixes the icons issue.
> 
> Please update the card and get back to me with results.

Good job 👍
