### ISSUE TITLE
Feature Request: Switch

### ISSUE THREAD

**Issue by Madseason41** [amaximus/transmission-card#3]
Nice card!

Any chance you could/ would add the transmission switches "turtle mode and pause" to the card?

Also the feedback that is presented on the torrent in the web ui would be cool to.

Great work!

**Comment by amaximus** [comment]
Feature added in 0.1.0.

Please upgade the card and get back to me with results.

**Comment by jurgenweber** [comment]
the buttons are cool man! Thanks!

**Comment by Madseason41** [comment]
Works great. Thanks man!
