### ISSUE TITLE
Change in transmission integration

### ISSUE THREAD

**Issue by crowley285** [amaximus/transmission-card#30]
Since Home Assistant 2022.12.7 I started getting this warning

The name key in Transmission services is being removed
Update any automations or scripts that use this service and replace the name key with the entry_id key.

**Comment by amaximus** [comment]
Thanks for the heads-up.
This warning comes from the integration, not the card as per [1]

Anyway I pushed a new release (0.9.0) that follows this change in the card as well.

Please update the card and get back to me with results.

[1] https://github.com/home-assistant/core/pull/78577

**Comment by SAOPP** [comment]
@amaximus are u sure 'bout the `entity_id` key? The `entry_id` key is specified in the documentation and in the changes.

**Comment by amaximus** [comment]
@SAOPP well, at least it's part of the entity_id key (pls see attached).
![transmission](https://user-images.githubusercontent.com/2511168/209538830-cfcd9bd1-2192-4cbd-a8e6-c25af2802998.PNG)

**Comment by SAOPP** [comment]
Ah, okay, it's right it's a part of entity_id, u mentioned it's like name --> entity_id, but in real case name --> entry if we 'r talkin' 'bout real service case, so, maybe I just missunderstood u'r message. :-)

![image](https://user-images.githubusercontent.com/5647009/209548473-30a33a33-9465-4a36-8471-59a417a66313.png)

**Comment by crowley285** [comment]
> Thanks for the heads-up. This warning comes from the integration, not the card as per [1]
> 
> Anyway I pushed a new release (0.9.0) that follows this change in the card as well.
> 
> Please update the card and get back to me with results.
> 
> [1] [home-assistant/core#78577](https://github.com/home-assistant/core/pull/78577)

I see, thanks for clarifying.
I pulled the new version of the card and it's working fine.
