### ISSUE TITLE
no sensor

### ISSUE THREAD

**Issue by urtaevS** [amaximus/transmission-card#35]
![image](https://user-images.githubusercontent.com/66906118/214580880-03854b5d-81bd-4c7c-a6b7-170ec9b08388.png)

I get this text with active torrents.
Maybe its because of name of integration?
`sensor.smartbox_active_torrents`

**Comment by amaximus** [comment]
Could you please provide your card definition?

**Comment by urtaevS** [comment]
> Could you please provide your card definition?

`type: custom:transmission-card
sensor_entity_id: smartbox
display_mode: compact
hide_header: true
default_type: active`

I have integration with two different name

**Comment by amaximus** [comment]
Please check in the Developer Tools -> States that the sensor sensor.smartbox_status exists and has a valid value.

**Comment by urtaevS** [comment]
> Please check in the Developer Tools -> States that the sensor sensor.smartbox_status exists and has a valid value.

![Screenshot_20230126-201033_Home_Assistant.png](https://user-images.githubusercontent.com/66906118/214902709-e91176a1-4dff-48b6-a366-0982d00fc31e.png)

**Comment by amaximus** [comment]
According to line 60, 69-75 (see [1]) ```no sensor``` is displayed for status if the down speed sensor's value (in your case sensor.smartbox_down_speed) is undefined. Did you disable this sensor?

https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L60

**Comment by urtaevS** [comment]
> According to line 60, 69-75 (see [1]) ```no sensor``` is displayed for status if the down speed sensor's value (in your case sensor.smartbox_down_speed) is undefined. Did you disable this sensor?
> 
> https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L60

![Screenshot_20230126-205949_Home_Assistant.png](https://user-images.githubusercontent.com/66906118/214913495-5b81ec1f-4c0d-4a1d-b7d0-6821bf39b0c2.png)

![Screenshot_20230126-205923_Home_Assistant.png](https://user-images.githubusercontent.com/66906118/214913518-a6519d56-52f8-46de-b244-c5a9dc77855d.png)

It's enabled :)

**Comment by amaximus** [comment]
Just pushed a new release (0.12.1) that addresses this issue.

Please update the card and get back to me with results.

**Comment by urtaevS** [comment]
> Just pushed a new release (0.12.1) that addresses this issue.
> 
> Please update the card and get back to me with results.

Many thanks for your work!

**Comment by amaximus** [comment]
Does it work as you expected?

**Comment by urtaevS** [comment]
> Does it work as you expected?

Yes, it's work properly!
