### ISSUE TITLE
Card not showing

### ISSUE THREAD

**Issue by migor7** [amaximus/transmission-card#36]
Card not showing in lovelaсe panel. If I go to the integration menu item, the card becomes visible until the page is refreshed. Home Assistant 2023.3.6
![torr1](https://user-images.githubusercontent.com/75983798/228783215-2e98be27-c9a1-4bd2-8382-6b2a5550abd4.jpg)

**Comment by amaximus** [comment]
Try to clear your browser cache and reload the UI.
Try to see in the browser's Developer Tools->Console if there are any errors related to this card.

**Comment by migor7** [comment]
I tried different browsers on different OS. Console is empty

**Comment by amaximus** [comment]
Please make sure you have the sensors sensor.transmission_* under Developer Tools -> States.

I just tried it in my test env and it works as expected:
![transmission](https://user-images.githubusercontent.com/2511168/229106316-519886ae-df5b-4ae1-a546-6973b0018577.PNG)

You may post your transmission card configuration.

**Comment by migor7** [comment]
![torr1](https://user-images.githubusercontent.com/75983798/229110684-10b8169e-5a00-4814-b9e8-d9f9657fed61.jpg)
![torr2](https://user-images.githubusercontent.com/75983798/229110694-c6a45dca-7c23-422c-895b-ceea085ad22b.jpg)

If I go to the integrations menu, the card is shown correctly until I refresh the page. Everything was working fine until I updated to 2023.3...
![torr3](https://user-images.githubusercontent.com/75983798/229110713-404c819b-a5e1-40dd-b302-7dc2fba63c8b.jpg)

**Comment by migor7** [comment]
> Hey,
> 
> Have the same problem, the problem seems to be when the setting "display_mode: full" is used, if you remove it, the card will work. The features from "display_mode: full" are nice though...
Yes, I can confirm. If remove full mode, then it works correctly

**Comment by amaximus** [comment]
@royto , do you know why the Transmission card's line 104
(https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L104) in full mode throws the following error?
```
transmission-card.js:104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at TransmissionCard._getConfigEntry (transmission-card.js:104:65)
    at TransmissionCard.renderTorrentButton (transmission-card.js:239:15)
    at TransmissionCard.renderTorrentFull (transmission-card.js:233:14)
    at transmission-card.js:160:50
    at Array.map (<anonymous>)
    at TransmissionCard.render (transmission-card.js:160:30)
    at TransmissionCard.update (lit-element.ts:160:24)
    at TransmissionCard.performUpdate (reactive-element.ts:1331:14)
    at TransmissionCard.scheduleUpdate (reactive-element.ts:1263:17)
    at TransmissionCard._$Ej (reactive-element.ts:1235:25)
```

**Comment by royto** [comment]
Hi, seems that `_entityRegistryDisplay`has been renamed to `_entityRegistryDisplay`
switching to 

````
const entityRegistry = this.hass.connection._entityRegistryDisplay.state.entities.find( x => x.ei = 'sensor.transmission_status' && x.pl === 'transmission')
    if (entityRegistry) {
      return entityRegistry.di;
    }
```

resolve the isse of displaying the card but start stop torrent seems to not work anymore ....

I'll take a look later to try to fix this

**Comment by royto** [comment]
I think I found a way to fix this. I'll create a PR soon

**Comment by amaximus** [comment]
Thanks.
