### ISSUE TITLE
Round speed sensor 

### ISSUE THREAD

**Issue by urtaevS** [amaximus/transmission-card#38]
How I can make sensor speed number shorter?
![Screenshot_2023-07-04-18-05-58-88_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/amaximus/transmission-card/assets/66906118/3313eb86-ab66-4839-ab8f-4f519ba8f4d6)

Like 0.2 MB/s instead 0.239777 MB/s

**Comment by Olegz73** [comment]
Need update card to use the display precision of HA. 
Please

**Comment by Olegz73** [comment]
Thank you. Look fine now

**Comment by urtaevS** [comment]
> I added a fix to round the speeds to one decimal.
> 
> Please update the card and get back to me with results.

I haven't checked yet, but I think it's fine!
Thank you!
