### ISSUE TITLE
Feature Request: Show ratio

### ISSUE THREAD

**Issue by hellcry37** [amaximus/transmission-card#4]
Please if you can add a field where the current ratio is shown for every torrent.
In my opinion this is all that is missing to be perfect.

**Comment by royto** [comment]
The ratio is not available in the torrents info provided by the transmission integration.

Need to be implemented first ...

**Comment by amaximus** [comment]
Yeah, thanks @royto , I was about to write the same.

**Comment by hellcry37** [comment]
Thank you, even without it you did a great job, it looks good.
