### ISSUE TITLE
Request: Option to hide the torrent list

### ISSUE THREAD

**Issue by Deathbot64** [amaximus/transmission-card#42]
It would be nice to be able to hide the torrent list, I currently have a card set up to add magnet links and show the up and down speeds but would like to not have the torrent list keep changing the size of the card.

**Comment by amaximus** [comment]
Newly pushed version (0.15.0) adds a parameter to hide the list of torrents.

Please update the card and get back to me with results.

**Comment by amaximus** [comment]
@Deathbot64 do you have any update on this issue?

**Comment by Deathbot64** [comment]
No issues from what I have seen. Thank you so much for adding this.
