### ISSUE TITLE
Sensor names are changed in HA

### ISSUE THREAD

**Issue by fustom** [amaximus/transmission-card#43]
The sensor names are changed with the following (merged and included to release from HA [2023.8.0b0](https://github.com/home-assistant/core/releases/tag/2023.8.0b0)) pull requests: https://github.com/home-assistant/core/pull/96761/files and https://github.com/home-assistant/core/pull/84664/files

I've got entities named:
- sensor.transmission_active_torrents
- sensor.transmission_completed_torrents
- sensor.transmission_download_speed
- sensor.transmission_paused_torrents
- sensor.transmission_started_torrents
- sensor.transmission_status
- switch.transmission_switch
- sensor.transmission_total_torrents
- switch.transmission_turtle_mode
- sensor.transmission_upload_speed 

You may have to implement some IF conditions to keep backward compatibility but support HA > 2023.08.0.

**Comment by amaximus** [comment]
Thanks for reporting this, I missed it from the release notes.

I just released version 0.15.2 that fixes this. Please update the card and get back to me with results.

**Comment by fustom** [comment]
https://github.com/amaximus/transmission-card/commit/d30a7a4c81cf66c1764fe8337e59b4ff00848642#commitcomment-126806506
