### ISSUE TITLE
'no torrents' while 39 are actually active

### ISSUE THREAD

**Issue by Jaykurb** [amaximus/transmission-card#46]
I have just created the card, but it says "no torrents' under every setting. However, if I check my transmission sensors, they are all showing active torrents etc. 

Is there something I'm missing during config?

**Comment by amaximus** [comment]
What your transmission sensors named?

**Comment by amaximus** [comment]
Try with: `sensor_id: transmission_macbook`.

**Comment by Jaykurb** [comment]
Of course, apologies. Thank you very much.
