### ISSUE TITLE
change torrent list sort

### ISSUE THREAD

**Issue by ivanjx** [amaximus/transmission-card#47]
is it possible to show latest -> oldest torrents instead of the current sorting?

**Comment by amaximus** [comment]
Newly released version 0.16.0 adds support for sorting the torrents list.

Please update the card and get back to me with results.

**Comment by amaximus** [comment]
Newly released version 0.17.0 moves configuration file control to UI.

**Comment by ivanjx** [comment]
sorry if i didnt phrase it correctly but im asking for support for sorting by added date descending. it works fine with ascending as it is the default behavior.

**Comment by amaximus** [comment]
@ivanjx  newest release 0.19.0 adds support for sort order (ascending/descending).

Please update the card, test it and get back to me with results.

**Comment by ivanjx** [comment]
i have this config but it does not affect the order properly yet (still ascending):
```
type: custom:transmission-card
default_sort: added_date
default_order: ascending
hide_add_torrent: true
```

**Comment by amaximus** [comment]
Something must br wrong on your side as it works for me:
* config set to yours:
```
(ha_venv3_11) pi@raspberrypi:~/homeassistant_test $tail -9 ui-lovelace.yaml
      - type: custom:transmission-card
        hide_type: false
        display_mode: 'full'
#        hide_torrent_list: true
#        hide_limit: false
#        hide_sort: false
#        hide_order: false
        default_sort: added_date
        default_order: descending
(ha_venv3_11) pi@raspberrypi:~/homeassistant_test $
```
* see Oppenheimer and 'For All Mankind ... S04E04 in the attached screenshots:
![t1](https://github.com/amaximus/transmission-card/assets/2511168/0542fc64-2ad2-487e-b36b-2feaa009cc76)
![t2](https://github.com/amaximus/transmission-card/assets/2511168/70b2a4ae-592b-47a3-8e1a-94bef28a08cb)

Please double-check your torrents information.

**Comment by ivanjx** [comment]
the problem seems to be what you are really using to sort with added date because it does not match at all

the card:
![image](https://github.com/amaximus/transmission-card/assets/12814796/404952b4-9580-4386-bb3a-b3067f436550)

transmission with added date ascending:
![image](https://github.com/amaximus/transmission-card/assets/12814796/c8b5a82e-d0ba-4922-a452-869149287856)

transmission with added date descending:
![Screenshot from 2023-12-26 18-43-54](https://github.com/amaximus/transmission-card/assets/12814796/01e2b1d5-d459-45c2-9117-3067aa7c25c1)

**Comment by amaximus** [comment]
Unfortunately, these screenshots do not show the attributes of the sensor with all their data (e.g. the added_date) as shown under the Developer Tools section.
Could you please run a similar command as below customized for your instance and provide its json output?
```
curl -s -k -X GET -H "Authorization: Bearer <your_token>" -H "Content-Type: application/json" http://<your_local_IP_address>:8123/api/states/sensor.transmission_total_torrents
```

**Comment by ivanjx** [comment]
the issue is your card:
1. lists all the torrents
2. **cuts** the result
3. sort it

where the correct way is to:
1. list the torrents
2. sort it
3. cut the result

**Comment by amaximus** [comment]
Let me double-check this.

**Comment by amaximus** [comment]
The card works correctly:
* lists all torrents in an array (lines 97-107) https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L97
* sorts the array (line 109) https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L109
* applies the cut on the sorted array (line 109) https://github.com/amaximus/transmission-card/blob/main/transmission-card.js#L109

If you want to test this, exclude the cut by not defining `default_limit` which will use `all` as default that will run on line 111 instead of line 109.

**Comment by ivanjx** [comment]
the problem seems to be the limit option here:
![image](https://github.com/amaximus/transmission-card/assets/12814796/8bb514ef-c93f-42ec-a079-f70c215d9d57)

any idea on how to unset the limit?

**Comment by amaximus** [comment]
Just put a positive number and click submit.

**Comment by ivanjx** [comment]
unfortunately it does not allow anything above 500. closing this since the issue is not with the card itself.
