### ISSUE TITLE
Download folder selection

### ISSUE THREAD

**Issue by Piedone86** [amaximus/transmission-card#48]
Hi there, I would ask your help to define the destination folder of the torrent while adding. E.g. I'm usually adding files to Plex, and "Movies" and "Tv Series" folders are differently scraped. That's why I would sort the different files to the proper folders. 
Thanks in advance for your help

**Comment by royto** [comment]
the card is calling the `add_torrent` service of transmission integration. Destination folder is not supported by the integration in HA. So it can be implemented until the option is available in HA tranmission integration
