### ISSUE TITLE
Card not showing

### ISSUE THREAD

**Issue by romquenin** [amaximus/transmission-card#49]
Hello my card is not showing even after HA full reboot and clear browser cache.

Here is my full config:

```
- url: /hacsfiles/transmission-card/transmission-card.js
  type: module
```
```
- type: custom:transmission-card
  hide_type: false
  default_type: "active"
  display_mode: compact
```
![Capture d’écran 2024-09-11 155828](https://github.com/user-attachments/assets/a54b4b1b-d885-4241-8017-588c6c7259e9)

**Comment by romquenin** [comment]
I have all the required sensors
![Capture d’écran 2024-09-11 155805](https://github.com/user-attachments/assets/077e9103-d7b8-41ee-a8d5-70cdfe8ee3a8)

**Comment by amaximus** [comment]
Hello, you should rename the sensor.transmission_statut to sensor.transmission_status.

**Comment by romquenin** [comment]
Thank you @amaximus i have renamed the sensor and it's working fine now.
