### ISSUE TITLE
Only one torrent visible

### ISSUE THREAD

**Issue by mikesrus** [amaximus/transmission-card#5]
After install via HACS i got this
![image](https://user-images.githubusercontent.com/15717372/100266883-9b609d00-2f63-11eb-81c1-f01a81a68cda.png)

i use Home assistant 0.117.6

**Comment by jurgenweber** [comment]
yeah, I get this also.. since v.03.

![image](https://user-images.githubusercontent.com/3013734/100285073-56b91e00-2fc4-11eb-98d1-8c1284c88722.png)
after my first 10 normal/working torrents

**Comment by amaximus** [comment]
Please upgrade the card to 0.1.1 and let me know if the issue still persists.

**Comment by jurgenweber** [comment]
yeah, the 'undefined' are gone for me now.. Thank you! Great work!
